export type InvestmentType =
  | 'stock'
  | 'ETF'
  | 'crypto'
  | 'cash'
  | 'real estate'
  | 'custom'
  | 'commodity'

// Commodity (bullion) sub-classification.
// Only meaningful when Investment.type === 'commodity'.
export type CommodityKind = 'gold' | 'silver'

// Unit in which the user is tracking commodity quantity.
// Yahoo metal feeds return price per troy ounce; if quantity_unit is 'gram',
// the price must be converted (divide by GRAMS_PER_TROY_OUNCE) before storing
// as current_price. This conversion is NOT done in this step — refresh logic
// is unchanged for now.
export type QuantityUnit = 'gram' | 'troy_ounce'

export type Investment = {
  id: string
  user_id: string
  name: string
  ticker: string | null
  type: InvestmentType
  platform: string
  current_price: number | null
  current_value: number | null
  currency: string
  price_last_updated_at: string | null
  price_source: string | null
  notes: string | null
  created_at: string
  updated_at: string
  // Commodity support (Step 1):
  // - Both fields are NULL for non-commodity rows.
  // - For type === 'commodity', both MUST be set (enforced by DB constraint).
  // - Forms / refresh / calculations are not yet wired up; these are storage only.
  commodity_kind: CommodityKind | null
  quantity_unit: QuantityUnit | null
}

export type InvestmentInput = {
  name: string
  ticker: string | null
  type: InvestmentType
  platform: string
  current_price: number | null
  current_value: number | null
  currency: string
  notes: string | null
  // Commodity support (Step 1): nullable on input, validated server-side later.
  commodity_kind: CommodityKind | null
  quantity_unit: QuantityUnit | null
}

export type TransactionType =
  | 'buy'
  | 'sell'
  | 'dividend'
  | 'deposit'
  | 'withdraw'
  | 'interest'
  | 'fee'
  | 'value update'

export type Transaction = {
  id: string
  user_id: string
  investment_id: string
  type: TransactionType
  quantity: number | null
  price_per_unit: number | null
  amount: number | null
  fee: number
  date: string
  notes: string | null
  created_at: string
  currency: string
  price_last_updated_at: string | null
  price_source: string | null
  // Phase 1 (mixed-currency support):
  // - For backfilled rows, price_currency and fee_currency equal the
  //   investment's currency (single-currency assumption preserved).
  // - For new rows inserted before Phase 2 ships, these are NULL — calculations
  //   fall back to investment.currency, which is the same behaviour as today.
  // - fx_rate_to_eur is NULL until Phase 2 starts snapshotting it on save.
  price_currency: string | null
  fee_currency: string | null
  fx_rate_to_eur: number | null
  // Populated when generated by the recurring-transactions cron; null for all
  // manually entered transactions.
  recurring_rule_id: string | null
  // Contribution tracking: true when the transaction represents new external
  // money entering the portfolio (not a reinvestment or reallocation).
  is_contribution: boolean
  contribution_source: string | null
}

export type FxRate = {
  currency: string
  eur_per_unit: number
  fetched_at: string
}

export type PortfolioSnapshot = {
  user_id: string
  date: string                  // 'YYYY-MM-DD'
  total_value_eur: number
  total_invested_eur: number
  total_realized_eur: number
  total_unrealized_eur: number
  total_ever_invested_eur: number
  snapshot_source: string
  created_at: string
  updated_at: string
}

// ---------------------------------------------------------------------------
// Recurring transactions
// ---------------------------------------------------------------------------

// MVP types only. Expand when adding sell / deposit / withdraw / interest.
export type RecurringTransactionType = 'buy' | 'fee'

export type RecurringFrequency = 'monthly' | 'weekly' | 'quarterly'

export type RecurringTransaction = {
  id: string
  user_id: string
  investment_id: string
  type: RecurringTransactionType
  frequency: RecurringFrequency
  // day_of_month: 1–28, set when frequency = 'monthly' | 'quarterly'
  day_of_month: number | null
  // day_of_week: 0–6 (0 = Monday), set when frequency = 'weekly'
  day_of_week: number | null
  start_date: string              // 'YYYY-MM-DD'
  end_date: string | null         // null = indefinite
  // For 'buy': exactly one of fixed_quantity / fixed_amount is non-null.
  // For 'fee': fixed_amount is non-null, fixed_quantity is null.
  fixed_quantity: number | null
  fixed_amount: number | null
  fixed_amount_currency: string | null
  fee: number
  fee_currency: string
  notes: string | null
  active: boolean
  // null = never generated; advances by one period each cron run.
  last_generated_date: string | null  // 'YYYY-MM-DD'
  created_at: string
  updated_at: string
}

export type InvestmentSnapshot = {
  user_id: string
  investment_id: string
  date: string
  value_eur: number
  remaining_cost_basis_eur: number
  realized_profit_eur: number
  unrealized_profit_eur: number
  quantity: number | null
  current_price_native: number | null
  currency: string
  snapshot_source: string
  created_at: string
  updated_at: string
}

// ---------------------------------------------------------------------------
// Capital flow ledger
// ---------------------------------------------------------------------------

export type CapitalFlowDirection = 'to_portfolio' | 'from_portfolio'

export type CapitalFlowEntry = {
  id: string
  user_id: string
  flow_date: string       // 'YYYY-MM-DD'
  year: number
  platform: string
  direction: CapitalFlowDirection
  amount_eur: number
  source: string | null
  notes: string | null
  created_at: string
}
